[project]
name = "sample-fastapi-mcp-server"
version = "0.1.0"
description = "sample-fastapi-mcp-server"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "mcp[cli]>=1.9.1",
]
